### PR TITLE
Added Black Wallet (Mobile Wallet Supporting BSC)

### PR DESCRIPTION
**Pull request by fallengravity**
Hi Docs Team,

I'm the lead developer on Black Wallet by Ether-1. We're a client-side, multicoin wallet supporting EVM based coins. We've recently implemented BSC and I thought it best to include a small guide on how to use BSC in our wallet on the docs site. 

If you'd like any modifications made, please let me know. 

Thanks!

### CODE REVIEW

**Review by hashratez — APPROVED** [review]
Wallet is looking really good.  A first class crypto wallet with amazing features and cross currency.  Everyone can use it.

**Comment by Crypto-Saiyan** [comment]
Sexy looking wallet,easy to use.

**Comment by dylie** [comment]
What is missing in order to get this pull request merged?

**Comment by OzzyBoganTech** [comment]
+1 looking good

**Comment by fallengravity** [comment]
Hey @huangsuyu, hope you're doing alright.

Would it be possible to let me know as to why this PR is being ignored? If there's something wrong with it please let me know so that I can make the needed changes instead of ghosting me.

Thanks.

**Review by Matthew123465 — APPROVED** [review]

**Review by Matthew123465 — APPROVED** [review]

**Review by Matthew123465 — APPROVED** [review]

**Review by Matthew123465 — APPROVED** [review]

**Comment by iakisme** [comment]
@fallengravity: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by iakisme** [comment]
@fallengravity: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by iakisme** [comment]
@fallengravity: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by iakisme** [comment]
@fallengravity: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by iakisme** [comment]
@fallengravity: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by iakisme** [comment]
@fallengravity: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by iakisme** [comment]
@fallengravity: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by iakisme** [comment]
@fallengravity: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request closed without merging**
